name: Test

on: [push, pull_request, workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Update pnpm
        run: npm i -g pnpm@latest

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install packages
        run: pnpm install

      - name: Test
        run: pnpm run test
